WebBanVeMayBay/WebBanVeMayBay/Controllers/DatVeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanVeMayBay.Models;

namespace WebBanVeMayBay.Controllers
{
    public class DatVeController : Controller
    {
        private WebBanVeMayBayDBContext db = new WebBanVeMayBayDBContext();
        // GET: DatVe
        [HttpGet]
        public ActionResult Index(int Id, string Name, string Date, string Time, int Price, string ClientName, string ClientId, string PhoneNumber)
        {
            var ticket = new Ticket()
            {
                PlanId = Id,
                ClientId = ClientId,
                PhoneNumber = PhoneNumber,
                ClientName = ClientName,
                PlanName = Name,
                Date = Date,
                Time = Time,
                Price = Price,
            };
            return View(ticket);
        }
        //public ActionResult CreateTicket()
        //{
        //    ViewBag.ListCat = new SelectList(db.Categories.ToList(), "Id", "Name");
        //    return View();
        //}

        public ActionResult CreateTicket(int PlanId, string PlanName, string Date, string Time, int Price, string ClientName, string ClientId, string PhoneNumber)
        {
            var ticket = new Ticket()
            {
                PlanId = PlanId,
                ClientId = ClientId,
                PhoneNumber = PhoneNumber,
                ClientName = ClientName,
                PlanName = PlanName,
                Date = Date,
                Time = Time,
                Price = Price,
            };
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTicket(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                //product.Created_At = DateTime.Now;
                ////product.Created_By = int.Parse(Session["UserId"].ToString());
                //product.Update_At = DateTime.Now;
                //product.Update_By = int.Parse(Session["UserId"].ToString());
                ticket.Status = 0;
                ticket.CreateDate = DateTime.Now;
                db.Ticket.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index", "Trangchu");
            }
            ViewBag.ListCat = new SelectList(db.Ticket.ToList(), "Id", "Name");
            return View(ticket);
        }

    }
}

WebBanVeMayBay/WebBanVeMayBay/Views/DatVe/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>Confirm</h2>

WebBanVeMayBay/WebBanVeMayBay/Views/DatVe/CreateTicket.cshtml
@model WebBanVeMayBay.Models.Ticket
@{
    ViewBag.Title = "CreateTicket";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Thông tin vé của bạn</strong>
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="row">
                <form class="form-card" onsubmit="event.preventDefault()">
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Mã chuyến bay: </label>
                            @Html.TextBoxFor(model => model.PlanId, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Id, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.PlanId, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Tên chuyến bay: </label>
                            @Html.TextBoxFor(model => model.PlanName, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Name, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.PlanName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Ngày bay: </label>
                            @Html.TextBoxFor(model => model.Date, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Date, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Giờ bay: </label>
                            @Html.TextBoxFor(model => model.Time, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Giá vé (Vnd): </label>
                            @Html.TextBoxFor(model => model.Price, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Họ tên: </label>
                            @Html.TextBoxFor(model => model.ClientName, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Căn cước công dân: </label>
                            @Html.TextBoxFor(model => model.ClientId, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label>Số điện thoại: </label>
                            @Html.TextBoxFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                            @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                        <p class="text-center text-danger font-weight-bold">*Vui lòng thanh toán tại quầy trong 72 giờ</p>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <a href="@Url.Action("Index", "Trangchu")" class="btn-block btn-success align-content-md-center mt-2 text-center p-1">Quay lại</a>
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <button type="submit" class="btn-block btn-success align-content-md-center mt-2" onclick="alert('Đặt vé thành công')">Xác nhận</button>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>
}

WebBanVeMayBay/WebBanVeMayBay/Views/DatVe/Index.cshtml
@model WebBanVeMayBay.Models.Ticket
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<body>
    <div class="container-fluid px-1 py-5 mx-auto">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                <div class="card">
                    <h3 class="text-center mb-4">Xác nhận thông tin đặt vé</h3>
                    @using (Html.BeginForm("CreateTicket", "DatVe", FormMethod.Get))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <form class="form-card" onsubmit="event.preventDefault()">
                        <div class="row justify-content-between text-left">
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Mã chuyến bay: </label>
                                @Html.TextBoxFor(model => model.PlanId, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Id, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.PlanId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Tên chuyến bay: </label>
                                @Html.TextBoxFor(model => model.PlanName, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Name, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.PlanName, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Ngày bay: </label>
                                @Html.TextBoxFor(model => model.Date, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Date, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Giờ bay: </label>
                                @Html.TextBoxFor(model => model.Time, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Giá vé (Vnd): </label>
                                @Html.TextBoxFor(model => model.Price, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Họ tên: </label>
                                @Html.TextBoxFor(model => model.ClientName, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Căn cước công dân: </label>
                                @Html.TextBoxFor(model => model.ClientId, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <label>Số điện thoại: </label>
                                @Html.TextBoxFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                @*@Html.DisplayFor(model => model.Time, "", new { @class = "text-danger" })*@
                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-sm-6 flex-column d-flex">
                                <a href="@Url.Action("Index", "Trangchu")" class="btn-block btn-success align-content-md-center mt-2 text-center p-1">Quay lại</a>
                            </div>
                            <div class="form-group col-sm-6 flex-column d-flex">
                                <button type="submit" class="btn-block btn-success align-content-md-center mt-2">Xác nhận</button>
                            </div>
                        </div>
                        @*<div class="form-group col-sm-6 flex-column d-flex pt-sm-4">
                                    <button type="submit" class="btn-block btn-success align-content-md-center mt-2">Đặt vé</button>
                                </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-12 flex-column d-flex pt-sm-4"> <a href="@Url.Action("Index", "Trangchu")" class="btn-block btn-success align-content-md-center mt-2 text-center ">Quay lại</a> </div>
                            </div>*@
                    </form>
                }
                </div>
            </div>
        </div>
    </div>
</body>