WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanVeMayBay.Models;
namespace WebBanVeMayBay.Areas.Admin.Controllers
{
    public class AuthController : Controller
    {
        // GET: Admin/Auth
        WebBanVeMayBayDBContext db = new WebBanVeMayBayDBContext();
        public ActionResult Login()
        {
            if (!Session["UserAdmin"].Equals(""))
            {
                return RedirectToAction("Index", "Product");
            }
            ViewBag.StrError = "";
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection field)
        {
            string strError = "";
            string username = field["username"];
            string password = MyString.ToMD5(field["password"]);

            User user = db.Users
                .Where(m => m.Status ==1 && m.UserName == username)
                .FirstOrDefault();
            if (user ==null)
            {
                strError = "Tên đăng nhập không tồn tại";
            }
            else
            {
                if (user.Password.Equals(password))
                {
                    Session["UserAdmin"] = user.UserName;
                    Session["UserId"] = user.Id;
                    Session["FullName"] = user.FullName;
                    return RedirectToAction("Index", "Product");
                }
                else strError = "Mật khẩu không chính xác";
            }

            ViewBag.StrError = "<span class='text-danger'>" + strError + "</span>";
            return View();
        }
        public ActionResult Logout()
        {
            Session["UserAdmin"] = "";
            Session["UserId"] = "";
            Session["FullName"] = "";
            return RedirectToAction("Login");
        }
    }
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanVeMayBay.Models;

namespace WebBanVeMayBay.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        private WebBanVeMayBayDBContext db = new WebBanVeMayBayDBContext();

        public ActionResult Index()
        {
            var list = db.Products
                .Join(
                    db.Categories,
                    p => p.CatId,
                    c => c.Id,
                    (p, c) => new ProductCategory
                    {
                        Id = p.Id,
                        Name = p.Name,
                        CatId = p.CatId,
                        Detail = p.Detail,
                        Number = p.Number,
                        Price = p.Price,
                        Pricesale = p.Pricesale,
                        Created_At = p.Created_At,
                        Created_By = p.Created_By,
                        Update_At = p.Update_At,
                        Update_By = p.Update_By,
                        Status = p.Status,
                        DateTime = p.DateTime,
                        MidAir = p.MidAir,
                        BreakTime = p.BreakTime,
                        Seat1 = p.Seat1,
                        Seat2 = p.Seat2,
                        OnAir = p.OnAir,
                        PlanTo = p.PlanTo,
                        PlanFrom = p.PlanFrom,
                        CatName = c.Name,
                    }
                )
                .Where(m => m.Status != 0).OrderByDescending(m => m.Created_At).ToList();
            return View(list);

        }
    }
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/Shared/_LayoutAd.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Public/css/LayoutAd.css" rel="stylesheet" />
    <link href="~/Public/css/css/all.min.css" rel="stylesheet" />
    @*<link href="~/Library/font-awesome.css" rel="stylesheet" />
        <link href="~/Library/style.css" rel="stylesheet" />*@
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("head", required: false)
    <style>
        .background-bar {
            background-color: #08403A; /*xanh*/
        }

        .background-bg {
            background-color: #D1D1D1; /*Xám*/
        }
    </style>
</head>
<body>
    <section class="clearfix header background-bar">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark background-bar">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">HQK ADMIN</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Dashboard")">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Chuyến bay
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Product")">Danh sách chuyến bay</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "Category")">Phân loại chuyến bay</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Create", "Product")">Thêm chuyến bay</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Create", "Category")">Thêm loại chuyến bay</a></li>
                                </ul>
                            </li>
                            @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Lập báo cáo
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "WeekReport")">Lập báo cáo tuần</a></li>
                                    <li><a class="dropdown-item" href="#">Lập báo cáo tháng</a></li>
                                    <li><a class="dropdown-item" href="#">Lập báo cáo quý</a></li>
                                    <li><a class="dropdown-item" href="#">Lập báo cáo năm</a></li>
                                </ul>
                            </li>*@
                            <li>
                                <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Ticket")">Vé chuyến bay</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Index", "Complain")">Giải quyết khiếu nại</a>
                            </li>
                        </ul>
                        <form class=" text-white">
                            @Session["Fullname"]
                            <a href="@Url.Action("Logout","Auth")" class="btn btn-sm- btn-success"> Đăng xuất </a>
                        </form>
                    </div>
                </div>
            </nav>
        </div>
    </section>
    <section class="clearfix maincontent background-bg">
        <div class="container-fluid py-3 ">
            @RenderBody()
        </div>
    </section>
    <section class="clearfix footer background-bar">
        <div class="container-fluid text-white text-center py-3">
            Design by HQK
        </div>
    </section>
    @RenderSection("Footer", required: false)
</body>
</html>

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <link href="~/Library/font-awesome.css" rel="stylesheet" />
    <link href="~/Library/style.css" rel="stylesheet" />
    <script src="~/Library/login.js"></script>
    <script src="~/Library/login1.js"></script>
    <link href="~/Library/login2.css" rel="stylesheet" />
    <link href="~/Library/login3.css" rel="stylesheet" />
    @RenderSection("head", required: false)
    <style>
        .background-bar {
            background-color: #08403A; /*xanh*/
        }

        .background-bg {
            background-color: #D1D1D1; /*Xám*/
        }
    </style>
</head>
<body>
    @RenderBody()
    <style>
        .background-bar {
            background-color: #08403A; /*xanh*/
        }

        .background-bg {
            background-color: #D1D1D1; /*Xám*/
        }
    </style>
</body>
</html>