WebBanVeMayBay/WebBanVeMayBay/Controllers/TrangchuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanVeMayBay.Models;
namespace WebBanVeMayBay.Controllers
{
    public class TrangchuController : Controller
    {
        private WebBanVeMayBayDBContext db = new WebBanVeMayBayDBContext();
        // GET: Trangchu
        public ActionResult Index()
        {
            var list = db.Products
                .Where(p => p.Status == 1)
                .Join(
                    db.Categories,
                    p => p.CatId,
                    c => c.Id,
                    (p, c) => new ProductCategory
                    {
                        Id = p.Id,
                        Name = p.Name,
                        CatId = p.CatId,
                        //Slug = p.Slug,
                        Detail = p.Detail,
                        //MetaDes = p.MetaDes,
                        //MetaKey = p.MetaKey,    
                        //Number = p.Number,
                        Price = p.Price,
                        //Pricesale = p.Pricesale,
                        Created_At = p.Created_At,
                        //Created_By = p.Created_By,
                        Update_At = p.Update_At,
                        //Update_By = p.Update_By,
                        Status = p.Status,
                        MidAir = p.MidAir,
                        BreakTime = p.BreakTime,
                        Seat1 = p.Seat1,
                        Seat2 = p.Seat2,
                        OnAir = p.OnAir,
                        PlanTo = p.PlanTo,
                        PlanFrom = p.PlanFrom,
                        DateTime = p.DateTime,
                        CatName = c.Name
                    }
                )
                .Where(m => m.Status != 0).OrderByDescending(m => m.Created_At).ToList();
            var productForHomePageViewModel = new ProductForHomePageViewModel()
            {
                ListPlanFrom = list.Select(x => new SelectListItem
                {
                    Value = x.CatId.ToString(),
                    Text = x.CatName,
                }).ToArray(),
                ListProductCategory = list,
                SeletedPlanFromId = default,
            };
            return View(productForHomePageViewModel);
        }
        public ActionResult Search(string SeletedPlanFromId, string SeletedPlanToId, DateTime date)
        {
            var list = (db.Products
                           .Where(s => s.PlanFrom.Contains(SeletedPlanFromId)
                                   && s.PlanTo.Contains(SeletedPlanToId)
                                   && DbFunctions.TruncateTime(s.DateTime) == date.Date))
                           .ToList();
            @ViewBag.c = list; 
            return View(list);
        }

        [HttpGet]
        public ActionResult DatVe(int id, string name, string date, string time, int Price)
        {
            var datve = new Datve()
            {
                Id = id,
                Name = name,
                Date = date,
                Time = time,
                Price = Price,
            };
            return View(datve);
        }
        public ActionResult Complain()
        {
            ViewBag.ListCat = new SelectList(db.Complain.ToList(), "Id", "Name");
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Complain(Complain complain)
        {
            if (ModelState.IsValid)
            {
                complain.CreateSend = DateTime.Now;
                complain.status = 0; //chưa giải quyết
                db.Complain.Add(complain);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ListCat = new SelectList(db.Complain.ToList(), "Id", "Name");
            return View(complain);
        }

        public ActionResult TicketSearch()
        {
            return View();
        }
        public ActionResult SearchTicketResult(string ClientId, string PhoneNumber)
        {
            var list = (db.Ticket.
                Where(s => s.ClientId == (ClientId) &&
                s.PhoneNumber == PhoneNumber));
            @ViewBag.c = list;
            return View(list);
        }
        public ActionResult Huyve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Ticket.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }
        [HttpPost, ActionName("Huyve")]
        [ValidateAntiForgeryToken]
        public ActionResult Huyve(int id)
        {
            Ticket ticket = db.Ticket.Find(id);
            db.Ticket.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebBanVeMayBay/WebBanVeMayBay/Views/Shared/_LayoutSite.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
</head>
<body>
    @RenderBody()
</body>
</html>*@
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <link href="~/Library/home.css" rel="stylesheet" />
    <script src="~/Library/home1.js"></script>
    <link href="~/Library/home2.css" rel="stylesheet" />
    <script src="~/Library/home3.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Public/css/LayoutAd.css" rel="stylesheet" />
    <link href="~/Public/css/css/all.min.css" rel="stylesheet" />
    <link href="~/Library/DatVe/Datve.css" rel="stylesheet" />
    @*<link href="~/Library/DatVe/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Library/DatVe/css/style.css" rel="stylesheet" />
        <img src="~/Library/DatVe/img/background.jpg" />*@

    @*<link href="~/Library/font-awesome.css" rel="stylesheet" />
        <link href="~/Library/style.css" rel="stylesheet" />*@
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("head", required: false)

    <style>
        .background-bar {
            background-color: #08403A; /*xanh*/
        }

        .background-bg {
            background-color: #D1D1D1; /*Xám*/
        }
    </style>
</head>
<body>
    <section class="clearfix header background-bar">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark background-bar">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">HQK</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Trangchu")">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Complain", "Trangchu")">Giải quyết khiếu nại</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("TicketSearch", "Trangchu")">Tra cứu vé</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </section>
    <section class="clearfix maincontent">
        <div class="container-fluid py-3">
            @RenderBody()
        </div>
    </section>
    <section class="clearfix footer background-bar">
        <div class="container-fluid text-black-50 text-center py-3">
            <a class="text-white">Design by HQK</a>
        </div>
    </section>
    @RenderSection("Footer", required: false)
</body>
</html>