WebBanVeMayBay/WebBanVeMayBay/Models/WeekReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WebBanVeMayBay.Models
{
    [Table("WeekReports")]
    public class WeekReport
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? Day { get; set; }
        public int Number { get; set; }
        public int Revenue { get; set; }
        public int Rate { get; set; }
        public int? Created_By { get; set; }
        public DateTime? Created_At { get; set; }
        public int? Update_By { get; set; }
        public DateTime? Update_At { get; set; }
    }
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Controllers/WeekReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanVeMayBay.Models;

namespace WebBanVeMayBay.Areas.Admin.Controllers
{
    public class WeekReportController : Controller
    {
        private WebBanVeMayBayDBContext db = new WebBanVeMayBayDBContext();

        // GET: Admin/WeekReport
        public ActionResult Index()
        {
            var list = db.WeekReport
               .OrderByDescending(c => c.Created_At)
               .ToList();
            return View("Index",list);
        }

        // GET: Admin/WeekReport/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeekReport weekReport = db.WeekReport.Find(id);
            if (weekReport == null)
            {
                return HttpNotFound();
            }
            return View(weekReport);
        }

        // GET: Admin/WeekReport/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/WeekReport/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Create( WeekReport weekReport)
        {
            if (ModelState.IsValid)
            {
                weekReport.Created_At = DateTime.Now;
                weekReport.Created_By = int.Parse(Session["UserAdmin"].ToString());
                weekReport.Update_At = DateTime.Now;
                weekReport.Update_By = int.Parse(Session["UserAdmin"].ToString());
                db.WeekReport.Add(weekReport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(weekReport);
        }

        // GET: Admin/WeekReport/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeekReport weekReport = db.WeekReport.Find(id);
            if (weekReport == null)
            {
                return HttpNotFound();
            }
            return View(weekReport);
        }

        // POST: Admin/WeekReport/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Day,Number,Revenue,Rate,Created_By,Created_At,Update_By,Update_At")] WeekReport weekReport)
        {
            if (ModelState.IsValid)
            {
                weekReport.Update_At = DateTime.Now;
                weekReport.Update_By = int.Parse(Session["UserAdmin"].ToString());
                db.Entry(weekReport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(weekReport);
        }

        // GET: Admin/WeekReport/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeekReport weekReport = db.WeekReport.Find(id);
            if (weekReport == null)
            {
                return HttpNotFound();
            }
            return View(weekReport);
        }

        // POST: Admin/WeekReport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WeekReport weekReport = db.WeekReport.Find(id);
            db.WeekReport.Remove(weekReport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/WeekReport/Create.cshtml
@model WebBanVeMayBay.Models.WeekReport

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Lập báo cáo Tuần</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "WeekReport")" class="btn btn-sm- btn-success">Trở lại danh sách</a>
                    <button type="submit" class="btn btn-sm btn-success">Lưu</button>
                </div>
            </div>
        </div>

        <div class="card-body p-3">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                        <label> Tên báo cáo</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Ngày</label>
                        <input id="day" type="datetime-local" name="day" />
                        @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Số vé bán</label>
                        @Html.TextAreaFor(model => model.Number, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                    </div>
                    
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Doanh thu</label>
                        @Html.TextAreaFor(model => model.Revenue, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Revenue, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Tỷ lệ</label>
                        @Html.TextAreaFor(model => model.Rate, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    </div>
        </div>
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/WeekReport/Delete.cshtml
@model WebBanVeMayBay.Models.WeekReport

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Xác nhận xóa</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Index", "Category")" class="btn btn-sm- btn-success">Trở lại danh sách</a>
                <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <div class="alert alert-warning">
            <strong> Thông báo </strong> Bạn có chắc muốn xóa thông tin này không?
        </div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Day)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Day)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Number)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Number)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Revenue)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Revenue)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Rate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Rate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created_By)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created_By)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created_At)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created_At)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Update_By)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Update_By)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Update_At)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Update_At)
            </dd>

        </dl>
    </div>


    @*@using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }*@
</div>
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/WeekReport/Details.cshtml
@model WebBanVeMayBay.Models.WeekReport

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WeekReport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Revenue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Revenue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_At)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_At)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Update_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Update_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Update_At)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Update_At)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/WeekReport/Edit.cshtml
@model WebBanVeMayBay.Models.WeekReport

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Created_At)
    @Html.HiddenFor(model => model.Created_By)

    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Chỉnh sửa báo cáo</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "WeekReport")" class="btn btn-sm- btn-success">Trở lại danh sách</a>
                    <button type="submit" class="btn btn-sm btn-success">Lưu</button>
                </div>
            </div>
        </div>

        <div class="card-body p-3">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                        <label> Tên báo cáo</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Ngày</label>
                        @Html.EditorFor(model => model.Day, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Tỷ lệ</label>
                        @Html.TextAreaFor(model => model.Rate, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                    </div>
                </div>      
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Số vé bán</label>
                        @Html.TextAreaFor(model => model.Number, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label> Doanh thu</label>
                        @Html.TextAreaFor(model => model.Revenue, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Revenue, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebBanVeMayBay/WebBanVeMayBay/Areas/Admin/Views/WeekReport/Index.cshtml
@model IEnumerable<WebBanVeMayBay.Models.WeekReport>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAd.cshtml";
}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Danh sách báo cáo Tuần</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create", "WeekReport")" class="btn btn-sm- btn-success">Thêm</a>
                @*<a href="@Url.Action("Trash", "Product")" class="btn btn-sm- btn-success">Thùng rác</a>*@
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <table class="table table-bordered table-hover">
            <thread>
                <tr>
                    <th style="width:20px;" class="text-center">#</th>
                    <th>Tên báo cáo</th>
                    <th>Ngày</th>
                    <th>Số vé bán</th>
                    <th>Doanh thu</th>
                    <th>Tỷ lệ</th>
                    <th class="text-center">Chức năng</th>
                    <th class="text-center">ID</th>

                </tr>

            </thread>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th style="width:20px;" class="text-center">
                            <input name="checkId" type="checkbox" />
                        </th>
                        <th>@item.Name</th>
                        <th>@item.Day</th>
                        <th>@item.Number</th>
                        <th>@item.Revenue</th>
                        <th>@item.Rate</th>
                        <th class="text-center">
                            <a href="@Url.Action("Edit", "WeekReport", new { @id = item.Id })" class="btn btn-sm btn-info ">
                                Chỉnh sửa
                            </a>
                            <a href="@Url.Action("Details", "WeekReport", new { @id = item.Id })" class="btn btn-sm btn-warning ">
                                Chi tiết
                            </a>
                            <a href="@Url.Action("Delete", "WeekReport", new { @id = item.Id })" class="btn btn-sm btn-danger ">
                                Xóa
                            </a>

                        </th>
                        <th class="text-center">@item.Id</th>

                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>